language: go
go:
 - 1.4
 - release
 - tip
install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/cenkalti/backoff
  - go get github.com/joho/godotenv
  - go get github.com/codegangsta/cli
env:
  - ENV=test
script:
  - go test -v ./...
